--- CREATING THE TABLES
CREATE TABLE PROPERTY (
    PROPERTYID INT NOT NULL PRIMARY KEY,
    OWNERID VARCHAR(12) NOT NULL,
    RENTPERMONTH INT,
    AVAILABLEFROM DATE,
    AVAILABLETILL DATE,
    TOTALAREA INT NOT NULL,
    PLINTHAREA INT NOT NULL,
    NOOFFLOORS INT,
    YEAROFCONSTRUCTION INT NOT NULL,
    LOCALITY VARCHAR(100),
    ADDRESS VARCHAR(500),
    ANNUALHIKE INT,
    RESIDENTIAL INT DEFAULT 0,
    NOOFBEDROOMS INT
);

CREATE TABLE USERS (
    AADHARID VARCHAR(12) PRIMARY KEY NOT NULL,
    LOGINID VARCHAR(15) NOT NULL,
    LOGINPASSWORD VARCHAR(15) NOT NULL,
    NAME VARCHAR(30),
    AGE INT,
    DOORNO INT,
    PINCODE INT,
    STREET VARCHAR(50),
    ISMANAGER INT DEFAULT 0,
    ISDBA INT DEFAULT 0
);

CREATE TABLE USERSPHONENUMBERS (
    AADHARID VARCHAR(12) NOT NULL,
    PHONENUMBER INT,
    CHECK(PHONENUMBER > 1000000000 AND PHONENUMBER <= 9999999999)
);

CREATE TABLE TENANTSHIP (
    RENTEDPROPERTYID INT NOT NULL,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    TENANTID VARCHAR(12) NOT NULL,
    RENTPERMONTH INT,
    YEARLYHIKE INT,
    AGENCYCOMMISSION INT
);
