CREATE OR REPLACE PROCEDURE GetRentHistory(
    P_PROPERTYID IN PROPERTY.PROPERTYID%TYPE
) AS
 G_LOOPVARIABLE NUMBER;
 G_RENTEDPROPERTYID PROPERTY.RENTEDPROPERTYID%TYPE;
 G_STARTDATE PROPERTY.STARTDATE%TYPE;
 G_ENDDATE PROPERTY.ENDDATE%TYPE;
 G_TENANTID PROPERTY.TENANTID%TYPE;
 G_RENTPERMONTH PROPERTY.RENTPERMONTH%TYPE;
 G_YEARLYHIKE PROPERTY.YEARLYHIKE%TYPE;
 G_AGENCYCOMMISSION PROPERTY.AGENCYCOMMISSION%TYPE;
BEGIN
    dbms_output.put_line('Property ID: '|| P_PROPERTYID);
    SELECT COUNT(*) INTO G_LOOPVARIABLE FROM TENANTSHIP WHERE PROPERTY.RENTEDPROPERTYID = P_PROPERTYID;
    LOOP
        SELECT (RENTEDPROPERTYID, STARTDATE, ENDDATE, TENANTID, RENTPERMONTH, YEARLYHIKE, AGENCYCOMMISSION) INTO (G_RENTEDPROPERTYID, G_STARTDATE, G_ENDDATE, G_TENANTID, G_RENTPERMONTH, G_YEARLYHIKE, G_AGENCYCOMMISSION) FROM TENANTSHIP WHERE RENTEDPROPERTYID = P_PROPERTYID;
        G_LOOPVARIABLE := G_LOOPVARIABLE - 1;
    EXIT WHEN G_LOOPVARIABLE = 0;
    END LOOP;
END;
/